<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TS_Login_CreateStore</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>c7717b71-ce85-4511-a94e-6fef2f0f067b</testSuiteGuid>
   <testCaseLink>
      <guid>013a1aa9-1b7b-4b88-8cf1-7b583b37b04b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TCShopify/TC03_LoginShopifyPartner</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>68dfe68c-9923-48c0-84a1-94d0fd28db4f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cffede4d-f013-439f-bb3e-de860330b97f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>5c05b845-6644-496c-9f10-e2e2836c4bc0</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TCShopify/TC04_CreateStoreShopify</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>2dcfeb5a-00af-4184-9b6b-b1f413247378</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Store name</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>2dcfeb5a-00af-4184-9b6b-b1f413247378</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>StoreName</value>
         <variableId>f597a8fb-f211-4856-9f44-27a411aee192</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
