<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>radio_Create_Store_Test_or_Build</name>
   <tag></tag>
   <elementGuidId>9aeb6fd1-1ba6-4d9e-9f30-aefc160c961e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul//li[2]//descendant::span[@class=&quot;Polaris-RadioButton__Backdrop&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
